export default [
  { id: 1, weight: 100, unit: "lbs", unitSystemId: 1 },
  { id: 2, weight: 55, unit: "lbs", unitSystemId: 1 },
  { id: 3, weight: 45, unit: "lbs", unitSystemId: 1 },
  { id: 4, weight: 35, unit: "lbs", unitSystemId: 1 },
  { id: 5, weight: 25, unit: "lbs", unitSystemId: 1 },
  { id: 6, weight: 15, unit: "lbs", unitSystemId: 1 },
  { id: 7, weight: 10, unit: "lbs", unitSystemId: 1 },
  { id: 8, weight: 5, unit: "lbs", unitSystemId: 1 },
  { id: 9, weight: 2.5, unit: "lbs", unitSystemId: 1 },
  { id: 10, weight: 1.25, unit: "lbs", unitSystemId: 1 },
  { id: 11, weight: 0.75, unit: "lbs", unitSystemId: 1 },
  { id: 12, weight: 0.50, unit: "lbs", unitSystemId: 1 },
  { id: 13, weight: 0.25, unit: "lbs", unitSystemId: 1 },
  { id: 14, weight: 50, unit: "kgs", unitSystemId: 2 },
  { id: 15, weight: 25, unit: "kgs", unitSystemId: 2 },
  { id: 16, weight: 20, unit: "kgs", unitSystemId: 2 },
  { id: 17, weight: 15, unit: "kgs", unitSystemId: 2 },
  { id: 18, weight: 10, unit: "kgs", unitSystemId: 2 },
  { id: 19, weight: 5, unit: "kgs", unitSystemId: 2 },
  { id: 20, weight: 2.5, unit: "kgs", unitSystemId: 2 },
  { id: 21, weight: 2, unit: "kgs", unitSystemId: 2 },
  { id: 22, weight: 1.5, unit: "kgs", unitSystemId: 2 },
  { id: 23, weight: 1, unit: "kgs", unitSystemId: 2 },
  { id: 24, weight: 0.5, unit: "kgs", unitSystemId: 2 },
  { id: 25, weight: 0.25, unit: "kgs", unitSystemId: 2 },
  { id: 26, weight: 0.125, unit: "kgs", unitSystemId: 2 },
]
