export default [
  { id: 1, weight: 100, unit: "lbs", unitSystem: "imperial" },
  { id: 2, weight: 55, unit: "lbs", unitSystem: "imperial" },
  { id: 3, weight: 45, unit: "lbs", unitSystem: "imperial" },
  { id: 4, weight: 35, unit: "lbs", unitSystem: "imperial" },
  { id: 5, weight: 25, unit: "lbs", unitSystem: "imperial" },
  { id: 6, weight: 15, unit: "lbs", unitSystem: "imperial" },
  { id: 7, weight: 10, unit: "lbs", unitSystem: "imperial" },
  { id: 8, weight: 5, unit: "lbs", unitSystem: "imperial" },
  { id: 9, weight: 2.5, unit: "lbs", unitSystem: "imperial" },
  { id: 10, weight: 1.25, unit: "lbs", unitSystem: "imperial" },
  { id: 11, weight: 0.75, unit: "lbs", unitSystem: "imperial" },
  { id: 12, weight: 0.50, unit: "lbs", unitSystem: "imperial" },
  { id: 13, weight: 0.25, unit: "lbs", unitSystem: "imperial" },
]
